/* Generated By:JavaCC: Do not edit this line. CSQLParserConstants.java */
package org.postgresql.stado.parser.core;

public interface CSQLParserConstants {

  int EOF = 0;
  int COMMENT_LINE = 5;
  int COMMENT_BLOCK = 6;
  int NOT_BITWISE_ = 7;
  int LESS_ = 8;
  int EQUALS_ = 9;
  int GREATER_ = 10;
  int OR_BITWISE_ = 11;
  int MINUS_ = 12;
  int SEMICOLON_ = 13;
  int FACTORIAL_ = 14;
  int DIVIDE_ = 15;
  int QUOTE = 16;
  int PARENTHESIS_START_ = 17;
  int PARENTHESIS_CLOSE_ = 18;
  int ABSOLUTE_ = 19;
  int STAR_ = 20;
  int AND_BITWISE_ = 21;
  int XOR_BITWISE_ = 22;
  int MODULO_ = 23;
  int PLUS_ = 24;
  int X_ = 25;
  int Y_ = 26;
  int Z_ = 27;
  int GIS_SAME_ = 28;
  int REGEX_MATCHES_CASE_INSTV_ = 29;
  int SHIFT_LEFT_BITWISE_ = 30;
  int LESS_EQUALS_ = 31;
  int NOT_EQUALS_2_ = 32;
  int GREATER_EQUALS_ = 33;
  int SHIFT_RIGHT_BITWISE_ = 34;
  int CONCAT_ = 35;
  int SQUARE_ROOT_ = 36;
  int REGEX_NOT_MATCHES_ = 37;
  int NOT_EQUALS_ = 38;
  int FACTORIAL_PREFIX_ = 39;
  int GIS_OVERLAPS_LEFT_ = 40;
  int GIS_OVERLAPS_RIGHT_ = 41;
  int GIS_OVERLAPS_ = 42;
  int AS_ = 43;
  int IN_ = 44;
  int IS_ = 45;
  int LN_ = 46;
  int NO_ = 47;
  int ON_ = 48;
  int OR_ = 49;
  int PI_ = 50;
  int TO_ = 51;
  int CONTAINED_WITHIN_OR_EQUALS_ = 52;
  int GIS_STRICT_BELOW_ = 53;
  int CONTAINS_OR_EQUALS_ = 54;
  int GIS_STRICT_ABOVE_ = 55;
  int CUBE_ROOT_ = 56;
  int GIS_OVERLAPS_ABOVE_ = 57;
  int REGEX_NOT_MATCHES_CASE_INSTV_ = 58;
  int LEFTOUTER_ = 59;
  int GIS_OVERLAPS_BELOW_ = 60;
  int ABS_ = 61;
  int ADD_ = 62;
  int AGE_ = 63;
  int ALL_ = 64;
  int AND_ = 65;
  int ANY_ = 66;
  int ASC_ = 67;
  int AVERAGE_ = 68;
  int BIT_ = 69;
  int CHR_ = 70;
  int COS_ = 71;
  int COT_ = 72;
  int CSV_ = 73;
  int DAY_ = 74;
  int DBA_ = 75;
  int DEC_ = 76;
  int DIV_ = 77;
  int END_ = 78;
  int EXP_ = 79;
  int FOR_ = 80;
  int INT_ = 81;
  int LOG_ = 82;
  int MAX_ = 83;
  int MD5_ = 84;
  int MIN_ = 85;
  int MOD_ = 86;
  int NOT_ = 87;
  int NOW_ = 88;
  int NUM_ = 89;
  int RAW_ = 90;
  int SET_ = 91;
  int SIN_ = 92;
  int SUM_ = 93;
  int TAN_ = 94;
  int ACOS_ = 95;
  int ASIN_ = 96;
  int ATAN_ = 97;
  int ATN2_ = 98;
  int BLOB_ = 99;
  int BOTH = 100;
  int BYTE_ = 101;
  int CASE_ = 102;
  int CAST_ = 103;
  int CBRT_ = 104;
  int CEIL_ = 105;
  int CHAR_ = 106;
  int CIDR_ = 107;
  int CLOB_ = 108;
  int COPY_ = 109;
  int CORR_ = 110;
  int COSH_ = 111;
  int DATE_ = 112;
  int DESC_ = 113;
  int DROP_ = 114;
  int ELSE_ = 115;
  int FROM_ = 116;
  int FULL_ = 117;
  int HOST_ = 118;
  int HOUR_ = 119;
  int INET_ = 120;
  int INT2_ = 121;
  int INT4_ = 122;
  int INT8_ = 123;
  int INTO_ = 124;
  int JOIN_ = 125;
  int KILL_ = 126;
  int LEFT_ = 127;
  int LIKE_ = 128;
  int LONG_ = 129;
  int LPAD_ = 130;
  int NODE_ = 131;
  int NULL_ = 132;
  int OIDS_ = 133;
  int PORT_ = 134;
  int REAL_ = 135;
  int RPAD_ = 136;
  int SHOW_ = 137;
  int SIGN_ = 138;
  int SOME_ = 139;
  int SQRT_ = 140;
  int SRID_ = 141;
  int ST_M_ = 142;
  int ST_X_ = 143;
  int ST_Y_ = 144;
  int ST_Z_ = 145;
  int TEMP_ = 146;
  int TEXT_ = 147;
  int THEN_ = 148;
  int TIME_ = 149;
  int TRAN_ = 150;
  int TRIM_ = 151;
  int TRUE_ = 152;
  int TYPE_ = 153;
  int USER_ = 154;
  int VIEW_ = 155;
  int WEEK_ = 156;
  int WHEN_ = 157;
  int WITH_ = 158;
  int WORK_ = 159;
  int YEAR_ = 160;
  int AFTER_ = 161;
  int ALTER_ = 162;
  int ASCII_ = 163;
  int ASKML_ = 164;
  int ATAN2_ = 165;
  int BEGIN_ = 166;
  int BOX2D_ = 167;
  int BOX3D_ = 168;
  int BTRIM_ = 169;
  int BYTEA_ = 170;
  int CHECK_ = 171;
  int CLOSE_ = 172;
  int COUNT_ = 173;
  int CROSS_ = 174;
  int EVERY_ = 175;
  int FALSE_ = 176;
  int FETCH_ = 177;
  int FIRST_ = 178;
  int FIXED_ = 179;
  int FLOAT_ = 180;
  int FLOOR_ = 181;
  int FORCE_ = 182;
  int GRANT_ = 183;
  int ILIKE_ = 184;
  int IMAGE_ = 185;
  int INDEX_ = 186;
  int INNER_ = 187;
  int INSTR_ = 188;
  int LEAST_ = 189;
  int LFILL_ = 190;
  int LIMIT_ = 191;
  int LOCAL_ = 192;
  int LOG10_ = 193;
  int LOWER_ = 194;
  int LTRIM_ = 195;
  int MONEY_ = 196;
  int MONTH_ = 197;
  int MULTI_ = 198;
  int NCHAR_ = 199;
  int NDIMS_ = 200;
  int NODES_ = 201;
  int OUTER_ = 202;
  int OWNER_ = 203;
  int POWER_ = 204;
  int QUOTE_STRING_ = 205;
  int RIGHT_ = 206;
  int ROUND_ = 207;
  int RTRIM_ = 208;
  int SCALE_ = 209;
  int STDIN_ = 210;
  int TABLE_ = 211;
  int TEMPDOT_ = 212;
  int TRUNC_ = 213;
  int UNION_ = 214;
  int UPPER_ = 215;
  int USING_ = 216;
  int VALUE_ = 217;
  int WHERE_ = 218;
  int ABBREV_ = 219;
  int AREA2D_ = 220;
  int ASEWKB_ = 221;
  int ASEWKT_ = 222;
  int ASTEXT_ = 223;
  int BIGINT_ = 224;
  int BINARY_ = 225;
  int BIT_OR_ = 226;
  int COLUMN_ = 227;
  int COMMIT_ = 228;
  int CONCAT_WORD = 229;
  int CREATE_ = 230;
  int CURSOR_ = 231;
  int DECODE_ = 232;
  int DELETE_ = 233;
  int DIRECT_ = 234;
  int ENCODE_ = 235;
  int WORD_EQUALS_ = 236;
  int ESCAPE_ = 237;
  int EXISTS_ = 238;
  int EXTENT_ = 239;
  int FAMILY_ = 240;
  int FLOAT4_ = 241;
  int FLOAT8_ = 242;
  int FREEZE_ = 243;
  int GLOBAL_ = 244;
  int HAVING_ = 245;
  int INSERT_ = 246;
  int ISRING_ = 247;
  int LENGTH_ = 248;
  int MANUAL_ = 249;
  int MINUTE_ = 250;
  int MODIFY_ = 251;
  int MODULE_ = 252;
  int NRINGS_ = 253;
  int NULLIF_ = 254;
  int NUMBER_ = 255;
  int OFFSET_ = 256;
  int PARENT_ = 257;
  int PUBLIC_ = 258;
  int RANDOM_ = 259;
  int RENAME_ = 260;
  int REPEAT_ = 261;
  int REVOKE_ = 262;
  int ROTATE_ = 263;
  int SECOND_ = 264;
  int SELECT_ = 265;
  int SERIAL_ = 266;
  int STDDEV_ = 267;
  int STDOUT_ = 268;
  int STRPOS_ = 269;
  int SUBSTR_ = 270;
  int TO_HEX_ = 271;
  int UNIQUE_ = 272;
  int UPDATE_ = 273;
  int VACUUM_ = 274;
  int VARBIT_ = 275;
  int WITHIN_ = 276;
  int ZMFLAG_ = 277;
  int ADDDATE_ = 278;
  int ADDTIME_ = 279;
  int ANALYZE_ = 280;
  int BETWEEN_ = 281;
  int BIT_AND_ = 282;
  int BOOL_OR_ = 283;
  int CEILING_ = 284;
  int CLUSTER_ = 285;
  int COLLECT_ = 286;
  int CONVERT_ = 287;
  int CURDATE_ = 288;
  int CURTIME_ = 289;
  int DAYNAME_ = 290;
  int DECIMAL_ = 291;
  int DECLARE_ = 292;
  int DEFAULT_ = 293;
  int DEGREE_ = 294;
  int EXPLAIN_ = 295;
  int EXTRACT_ = 296;
  int GET_BIT_ = 297;
  int INHERIT_ = 298;
  int INITCAP_ = 299;
  int INTEGER_ = 300;
  int ISEMPTY_ = 301;
  int ISVALID_ = 302;
  int LEADING = 303;
  int MACADDR_ = 304;
  int MAPCHAR_ = 305;
  int MASKLEN_ = 306;
  int NATURAL_ = 307;
  int NETMASK_ = 308;
  int NETWORK_ = 309;
  int NPOINTS_ = 310;
  int NUMERIC_ = 311;
  int OVERLAY_ = 312;
  int PLACING_ = 313;
  int PREPARE_ = 314;
  int PUBLICDOT_ = 315;
  int QUARTER_ = 316;
  int RADIANS_ = 317;
  int REGR_R2_ = 318;
  int REPLACE_ = 319;
  int ROTATEX_ = 320;
  int ROTATEY_ = 321;
  int ROTATEZ_ = 322;
  int SET_BIT_ = 323;
  int SETSEED_ = 324;
  int SETSRID_ = 325;
  int SOUNDEX_ = 326;
  int SPATIAL_ = 327;
  int ST_AREA_ = 328;
  int STORAGE_ = 329;
  int ST_SRID_ = 330;
  int ST_TEXT_ = 331;
  int SUBDATE_ = 332;
  int SUBTIME_ = 333;
  int TINYINT_ = 334;
  int TO_CHAR_ = 335;
  int TO_DATE_ = 336;
  int VARCHAR_ = 337;
  int VAR_POP_ = 338;
  int VARYING_ = 339;
  int VERBOSE_ = 340;
  int VERSION_ = 341;
  int ADD_NODE_ = 342;
  int ASBINARY_ = 343;
  int BOOL_AND_ = 344;
  int COALESCE_ = 345;
  int CONTAINS_ = 346;
  int DATABASE_ = 347;
  int DATEDIFF_ = 348;
  int DATETIME_ = 349;
  int DESCRIBE_ = 350;
  int DISJOINT_ = 351;
  int DISTANCE_ = 352;
  int DISTINCT_ = 353;
  int DROPBBOX_ = 354;
  int ENDPOINT_ = 355;
  int ENVELOPE_ = 356;
  int EXTENT3D_ = 357;
  int FORCE_2D_ = 358;
  int FORCE_3D_ = 359;
  int FORCE_4D_ = 360;
  int GEOMETRY_ = 361;
  int GET_BYTE_ = 362;
  int GREATEST_ = 363;
  int HOSTMASK_ = 364;
  int INHERITS_ = 365;
  int INTERVAL_ = 366;
  int ISCLOSED_ = 367;
  int ISFINITE_ = 368;
  int ISSIMPLE_ = 369;
  int LAST_DAY_ = 370;
  int LENGTH2D_ = 371;
  int LENGTH3D_ = 372;
  int LOCATION_ = 373;
  int LONG_RAW_ = 374;
  int LONGTEXT_ = 375;
  int LVARCHAR_ = 376;
  int MEM_SIZE_ = 377;
  int NATIONAL_ = 378;
  int NEXT_DAY_ = 379;
  int OVERLAPS_ = 380;
  int PASSWORD_ = 381;
  int REGCLASS_ = 382;
  int REGR_SXX_ = 383;
  int REGR_SXY_ = 384;
  int REGR_SYY_ = 385;
  int RESOURCE_ = 386;
  int ROLLBACK_ = 387;
  int SET_BYTE_ = 388;
  int SETPOINT_ = 389;
  int SHUT_DOWN_ = 390;
  int SIMPLIFY_ = 391;
  int SMALLINT_ = 392;
  int STANDARD_ = 393;
  int ST_ASGML_ = 394;
  int ST_ASKML_ = 395;
  int ST_ASSVG_ = 396;
  int ST_BOX2D_ = 397;
  int ST_BOX3D_ = 398;
  int ST_BYTEA_ = 399;
  int ST_MULTI_ = 400;
  int ST_NDIMS_ = 401;
  int ST_POINT_ = 402;
  int ST_SCALE_ = 403;
  int ST_WIDTH_ = 404;
  int TINYTEXT_ = 405;
  int TO_ASCII_ = 406;
  int TRAILING = 407;
  int TRUNCATE_ = 408;
  int UNLISTEN_ = 409;
  int UNSIGNED_ = 410;
  int VARCHAR2_ = 411;
  int VARIANCE_ = 412;
  int VAR_SAMP_ = 413;
  int ZEROFILL_ = 414;
  int ASHEXEWKB_ = 415;
  int BIGSERIAL_ = 416;
  int BROADCAST_ = 417;
  int CHARACHTER_ = 418;
  int COVAR_POP_ = 419;
  int DATEPART_ = 420;
  int DAYOFWEEK_ = 421;
  int DAYOFYEAR_ = 422;
  int DELIMITER_ = 423;
  int DIMENSION_ = 424;
  int DROP_NODE_ = 425;
  int FORCE_3DM_ = 426;
  int FORCE_3DZ_ = 427;
  int GEOMETRYN_ = 428;
  int LINEMERGE_ = 429;
  int LOCALTIME_ = 430;
  int MONTHNAME_ = 431;
  int QPUBLICDOT_ = 432;
  int REGR_AVGX_ = 433;
  int REGR_AVGY_ = 434;
  int ST_AFFINE_ = 435;
  int ST_AREA2D_ = 436;
  int ST_ASEWKB_ = 437;
  int ST_ASEWKT_ = 438;
  int ST_ASTEXT_ = 439;
  int ST_BUFFER_ = 440;
  int ST_COVERS_ = 441;
  int ST_EQUALS_ = 442;
  int ST_EXTENT_ = 443;
  int ST_FACTOR_ = 444;
  int ST_HASARC_ = 445;
  int ST_HEIGHT_ = 446;
  int ST_ISRING_ = 447;
  int ST_LENGTH_ = 448;
  int ST_NRINGS_ = 449;
  int ST_POINTN_ = 450;
  int ST_RELATE_ = 451;
  int ST_ROTATE_ = 452;
  int ST_WITHIN_ = 453;
  int ST_ZMFLAG_ = 454;
  int SUBSTRING_ = 455;
  int TEMPORARY_ = 456;
  int TIMEOFDAY_ = 457;
  int TIMESTAMP_ = 458;
  int TO_NUMBER_ = 459;
  int TRANSFORM_ = 460;
  int TRANSLATE_ = 461;
  int VARBINARY_ = 462;
  int ADD_MONTHS_ = 463;
  int BIGINTEGER_ = 464;
  int BIT_LENGTH_ = 465;
  int BITVARYING_ = 466;
  int CONSTRAINT_ = 467;
  int COVAR_SAMP_ = 468;
  int DATETRUNC_ = 469;
  int DAYOFMONTH_ = 470;
  int DEALLOCATE_ = 471;
  int DIFFERENCE_ = 472;
  int INTERSECTS_ = 473;
  int MEDIUMTEXT_ = 474;
  int REFERENCES_ = 475;
  int REGR_COUNT_ = 476;
  int REGR_SLOPE_ = 477;
  int REPLICATED_ = 478;
  int SEGMENTIZE_ = 479;
  int SMALLFLOAT_ = 480;
  int SMALLMONEY_ = 481;
  int SNAPTOGRID_ = 482;
  int SPLIT_PART_ = 483;
  int STARTPOINT_ = 484;
  int STATISTICS_ = 485;
  int ST_AZIMUTH_ = 486;
  int ST_CHIP_IN_ = 487;
  int ST_COLLECT_ = 488;
  int ST_CROSSES_ = 489;
  int STDDEV_POP_ = 490;
  int ST_DWITHIN_ = 491;
  int ST_GEOHASH_ = 492;
  int ST_ISEMPTY_ = 493;
  int ST_ISVALID_ = 494;
  int ST_NPOINTS_ = 495;
  int ST_POLYGON_ = 496;
  int ST_REVERSE_ = 497;
  int ST_ROTATEX_ = 498;
  int ST_ROTATEY_ = 499;
  int ST_ROTATEZ_ = 500;
  int ST_SETSRID_ = 501;
  int ST_SUMMARY_ = 502;
  int ST_TOUCHES_ = 503;
  int TABLESPACE_ = 504;
  int TRANSSCALE_ = 505;
  int WEEKOFYEAR_ = 506;
  int BOX3DEXTENT_ = 507;
  int CHAR_LENGTH_ = 508;
  int PERIMETER2D_ = 509;
  int PERIMETER3D_ = 510;
  int QUOTE_IDENT_ = 511;
  int REMOVEPOINT_ = 512;
  int SET_MASKLEN_ = 513;
  int ST_ADDPOINT_ = 514;
  int ST_ASBINARY_ = 515;
  int ST_BOUNDARY_ = 516;
  int ST_CENTROID_ = 517;
  int ST_CHIP_OUT_ = 518;
  int ST_CONTAINS_ = 519;
  int ST_COORDDIM_ = 520;
  int ST_DATATYPE_ = 521;
  int STDDEV_SAMP_ = 522;
  int ST_DISJOINT_ = 523;
  int ST_DISTANCE_ = 524;
  int ST_ENDPOINT_ = 525;
  int ST_ENVELOPE_ = 526;
  int ST_EXTENT3D_ = 527;
  int ST_FORCE_2D_ = 528;
  int ST_FORCE_3D_ = 529;
  int ST_FORCE_4D_ = 530;
  int ST_FORCERHR_ = 531;
  int ST_GEOMETRY_ = 532;
  int ST_GMLTOSQL_ = 533;
  int ST_ISCLOSED_ = 534;
  int ST_ISSIMPLE_ = 535;
  int ST_LENGTH2D_ = 536;
  int ST_LENGTH3D_ = 537;
  int ST_MEM_SIZE_ = 538;
  int ST_OVERLAPS_ = 539;
  int ST_SETPOINT_ = 540;
  int ST_SIMPLIFY_ = 541;
  int ST_WKBTOSQL_ = 542;
  int ST_WKTTOSQL_ = 543;
  int TRANSACTION_ = 544;
  int CURRENTDATE_ = 545;
  int CURRENT_TIME_ = 546;
  int CURRENT_USER_ = 547;
  int EXTERIORRING_ = 548;
  int GEOMETRYTYPE_ = 549;
  int GEOMFROMEWKT_ = 550;
  int GEOMFROMTEXT_ = 551;
  int INTERSECTION_ = 552;
  int JUSTIFY_DAYS_ = 553;
  int LONG_VARCHAR_ = 554;
  int OCTET_LENGTH_ = 555;
  int SERIALIZABLE_ = 556;
  int ST_ASGEOJSON_ = 557;
  int ST_ASHEXEWKB_ = 558;
  int ST_BUILDAREA_ = 559;
  int ST_COVEREDBY_ = 560;
  int ST_DIMENSION_ = 561;
  int ST_FORCE_3DM_ = 562;
  int ST_FORCE_3DZ_ = 563;
  int ST_GEOMETRYN_ = 564;
  int ST_LINEMERGE_ = 565;
  int ST_MAKEPOINT_ = 566;
  int ST_NUMPOINTS_ = 567;
  int ST_PERIMETER_ = 568;
  int ST_SETFACTOR_ = 569;
  int ST_TRANSFORM_ = 570;
  int ST_TRANSLATE_ = 571;
  int TO_TIMESTAMP_ = 572;
  int VARIANCE_POP_ = 573;
  int WIDTH_BUCKET_ = 574;
  int INTERIORRINGN_ = 575;
  int JUSTIFY_HOURS_ = 576;
  int NUMGEOMETRIES_ = 577;
  int QUOTE_LITERAL_ = 578;
  int SAMLLDATETIME_ = 579;
  int ST_ADDMEASURE_ = 580;
  int ST_CONVEXHULL_ = 581;
  int ST_DIFFERENCE_ = 582;
  int ST_INTERSECTS_ = 583;
  int ST_MAKEPOINTM_ = 584;
  int ST_MEMCOLLECT_ = 585;
  int ST_SEGMENTIZE_ = 586;
  int ST_SNAPTOGRID_ = 587;
  int ST_STARTPOINT_ = 588;
  int ST_TRANSSCALE_ = 589;
  int SYMDIFFERENCE_ = 590;
  int VARIANCE_SAMP_ = 591;
  int CURRENT_SCHEMA_ = 592;
  int LINE_SUBSTRING_ = 593;
  int LOCALTIMESTAMP_ = 594;
  int MONTHS_BETWEEN_ = 595;
  int REGEXP_REPLACE_ = 596;
  int REGR_INTERCEPT_ = 597;
  int ST_COMPRESSION_ = 598;
  int ST_CURVETOLINE_ = 599;
  int ST_FIND_EXTENT_ = 600;
  int ST_GEOGFROMWKB_ = 601;
  int ST_GEOMFROMGML_ = 602;
  int ST_GEOMFROMKML_ = 603;
  int ST_GEOMFROMWKB_ = 604;
  int ST_LINEFROMWKB_ = 605;
  int ST_LINETOCURVE_ = 606;
  int ST_LONGESTLINE_ = 607;
  int ST_MAKEPOLYGON_ = 608;
  int ST_MAXDISTANCE_ = 609;
  int ST_PERIMETER2D_ = 610;
  int ST_PERIMETER3D_ = 611;
  int ST_POLYFROMWKB_ = 612;
  int ST_REMOVEPOINT_ = 613;
  int CLOCK_TIMESTAMP_ = 614;
  int ST_CLOSESTPOINT_ = 615;
  int ST_COMBINE_BBOX_ = 616;
  int ST_DFULLYWITHIN_ = 617;
  int ST_EXTERIORRING_ = 618;
  int ST_GEOGFROMTEXT_ = 619;
  int ST_GEOMETRYTYPE_ = 620;
  int ST_GEOMFROMEWKB_ = 621;
  int ST_GEOMFROMEWKT_ = 622;
  int ST_GEOMFROMTEXT_ = 623;
  int ST_INTERSECTION_ = 624;
  int ST_LINEFROMTEXT_ = 625;
  int ST_MAKEENVELOPE_ = 626;
  int ST_MLINEFROMWKB_ = 627;
  int ST_MPOLYFROMWKB_ = 628;
  int ST_POINTFROMWKB_ = 629;
  int ST_POLYFROMTEXT_ = 630;
  int ST_SHORTESTLINE_ = 631;
  int CHARACTER_LENGTH_ = 632;
  int CURRENT_DATABASE_ = 633;
  int FORCE_COLLECTION_ = 634;
  int JUSTIFY_INTERVAL_ = 635;
  int NUMINTERIORRINGS_ = 636;
  int POSTGIS_DROPBBOX_ = 637;
  int ST_INTERIORRINGN_ = 638;
  int ST_ISVALIDREASON_ = 639;
  int ST_MLINEFROMTEXT_ = 640;
  int ST_MPOINTFROMWKB_ = 641;
  int ST_MPOLYFROMTEXT_ = 642;
  int ST_NUMGEOMETRIES_ = 643;
  int ST_POINTFROMTEXT_ = 644;
  int ST_SYMDIFFERENCE_ = 645;
  int ADDGEOMETRYCOLUMN_ = 646;
  int CURRENT_TIMESTAMP_ = 647;
  int LINE_LOCATE_POINT_ = 648;
  int ST_BDPOLYFROMTEXT_ = 649;
  int ST_LINE_SUBSTRING_ = 650;
  int ST_MPOINTFROMTEXT_ = 651;
  int ST_ORDERINGEQUALS_ = 652;
  int ST_POINTONSURFACE_ = 653;
  int ST_POLYGONFROMWKB_ = 654;
  int PG_CLIENT_ENCODING_ = 655;
  int ST_BDMPOLYFROMTEXT_ = 656;
  int ST_DISTANCE_SPHERE_ = 657;
  int ST_GEOMCOLLFROMWKB_ = 658;
  int ST_LENGTH_SPHEROID_ = 659;
  int ST_NUMINTERIORRING_ = 660;
  int ST_POLYGONFROMTEXT_ = 661;
  int ST_SHIFT_LONGITUDE_ = 662;
  int STATEMENT_TIMESTAMP_ = 663;
  int ST_CONTAINSPROPERLY_ = 664;
  int ST_FORCE_COLLECTION_ = 665;
  int ST_GEOMCOLLFROMTEXT_ = 666;
  int ST_MULTILINEFROMWKB_ = 667;
  int ST_MULTIPOLYFROMWKB_ = 668;
  int ST_NUMINTERIORRINGS_ = 669;
  int ST_POSTGIS_GIST_SEL_ = 670;
  int LOCATE_ALONG_MEASURE_ = 671;
  int ST_COLLECTIONEXTRACT_ = 672;
  int ST_DISTANCE_SPHEROID_ = 673;
  int ST_GEOGRAPHYFROMTEXT_ = 674;
  int ST_HAUSDORFFDISTANCE_ = 675;
  int ST_LENGTH2D_SPHEROID_ = 676;
  int ST_LENGTH3D_SPHEROID_ = 677;
  int ST_LINE_LOCATE_POINT_ = 678;
  int ST_LINESTRINGFROMWKB_ = 679;
  int ST_MULTIPOINTFROMWKB_ = 680;
  int ST_LINEFROMMULTIPOINT_ = 681;
  int ST_MULTIPOINTFROMTEXT_ = 682;
  int TRANSACTION_TIMESTAMP_ = 683;
  int LINE_INTERPOLATE_POINT_ = 684;
  int ST_POINT_INSIDE_CIRCLE_ = 685;
  int ST_SYMMETRICDIFFERENCE_ = 686;
  int LOCATE_BETWEEN_MEASURES_ = 687;
  int ST_LOCATE_ALONG_MEASURE_ = 688;
  int ST_MULTIPOLYGONFROMTEXT_ = 689;
  int ST_POSTGIS_GIST_JOINSEL_ = 690;
  int ST_LINECROSSINGDIRECTION_ = 691;
  int ST_MINIMUMBOUNDINGCIRCLE_ = 692;
  int ST_LINE_INTERPOLATE_POINT_ = 693;
  int ST_LOCATEBETWEENELEVATIONS_ = 694;
  int ST_LOCATE_BETWEEN_MEASURES_ = 695;
  int ST_MULTILINESTRINGFROMTEXT_ = 696;
  int ST_SIMPLIFYPRESERVETOPOLOGY_ = 697;
  int UNARY_SIGN_ = 698;
  int ORDER_BY_ = 699;
  int UPDATE_STAT_ = 700;
  int PRIMARYKEY_ = 701;
  int FOREIGNKEY_ = 702;
  int PARTITIONINGKEY_ = 703;
  int ROUND_ROBIN_ = 704;
  int WITH_XROWID_ = 705;
  int WITHOUT_XROWID_ = 706;
  int PARTITION_WITH_ = 707;
  int START_DB_ = 708;
  int WAIT_TIMEOUT_ = 709;
  int STOP_DB_ = 710;
  int CREATE_DB_ = 711;
  int CREATE_NODE_ = 712;
  int DROP_DB_ = 713;
  int SHOW_AGENTS_ = 714;
  int SHOW_STATEMENTS_ = 715;
  int SHOW_DATABASES_ = 716;
  int SHOW_TABLES_ = 717;
  int SHOW_TRAN_ISOLATION_ = 718;
  int REPEATABLE_READ_ = 719;
  int READ_COMMITTED_ = 720;
  int READ_UNCOMMITTED_ = 721;
  int ISOLATION_LEVEL_ = 722;
  int SHOW_CONSTRAINTS_ = 723;
  int OWNER_TO_ = 724;
  int SHOW_TABLE_ = 725;
  int SHOW_VIEW_ = 726;
  int SHOW_VIEWS_ = 727;
  int SHOW_USERS_ = 728;
  int FORCE_NOT_NULL_ = 729;
  int FORCE_QUOTE_ = 730;
  int ON_COMMIT_ = 731;
  int PRESERVE_ROWS_ = 732;
  int DELETE_ROWS_ = 733;
  int GROUP_BY_ = 734;
  int EXEC_ = 735;
  int SIMILAR_TO_ = 736;
  int SHOW_INDEXES_ = 737;
  int WITH_TIMEZONE_ = 738;
  int WITHOUT_TIMEZONE_ = 739;
  int DOUBLE_PRECISION_ = 740;
  int BOOLEAN_ = 741;
  int YEAR_FROM = 742;
  int QUARTER_FROM = 743;
  int MONTH_FROM = 744;
  int WEEK_FROM = 745;
  int DAY_FROM = 746;
  int DOY_FROM = 747;
  int DOW_FROM = 748;
  int DECADE_FROM = 749;
  int CENTURY_FROM = 750;
  int HOUR_FROM = 751;
  int MINUTE_FROM = 752;
  int SECOND_FROM = 753;
  int MILLISECOND_FROM = 754;
  int MILLENNIUM_FROM = 755;
  int MICROSECONDS_FROM = 756;
  int EPOCH_FROM = 757;
  int POSITION_ = 758;
  int VALUES_ = 759;
  int SINGLEDIGIT = 760;
  int INT_LITERAL = 761;
  int DECIMAL_LITERAL = 762;
  int SCIENTIFIC_LITERAL = 763;
  int STRING_LITERAL = 764;
  int PARAM_PLACE_HOLDER = 765;
  int INTERVAL_LITERAL = 766;
  int DATE_LITERAL = 767;
  int TIME_LITERAL = 768;
  int TIMESTAMP_LITERAL = 769;
  int TEXT_LITERAL = 770;
  int INTEGER_LITERAL = 771;
  int MACADDR_LITERAL = 772;
  int CIDR_LITERAL = 773;
  int INET_LITERAL = 774;
  int GEOMETRY_LITERAL = 775;
  int BINARY_LITERAL = 776;
  int HEXDECIMAL_LITERAL = 777;
  int LETTER = 778;
  int IDENTIFIER = 779;
  int QUOTED_IDENTIFIER = 780;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMMENT_LINE>",
    "<COMMENT_BLOCK>",
    "\"~\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"|\"",
    "\"-\"",
    "\";\"",
    "\"!\"",
    "\"/\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "\"*\"",
    "\"&\"",
    "\"#\"",
    "\"%\"",
    "\"+\"",
    "\"X\"",
    "\"Y\"",
    "\"Z\"",
    "\"~=\"",
    "\"~*\"",
    "\"<<\"",
    "\"<=\"",
    "\"<>\"",
    "\">=\"",
    "\">>\"",
    "\"||\"",
    "\"|/\"",
    "\"!~\"",
    "\"!=\"",
    "\"!!\"",
    "\"&<\"",
    "\"&>\"",
    "\"&&\"",
    "\"AS\"",
    "\"IN\"",
    "\"IS\"",
    "\"LN\"",
    "\"NO\"",
    "\"ON\"",
    "\"OR\"",
    "\"PI\"",
    "\"TO\"",
    "\"<<=\"",
    "\"<<|\"",
    "\">>=\"",
    "\"|>>\"",
    "\"||/\"",
    "\"|&>\"",
    "\"!~*\"",
    "\"(+)\"",
    "\"&<|\"",
    "\"ABS\"",
    "\"ADD\"",
    "\"AGE\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"ASC\"",
    "\"AVG\"",
    "\"BIT\"",
    "\"CHR\"",
    "\"COS\"",
    "\"COT\"",
    "\"CSV\"",
    "\"DAY\"",
    "\"DBA\"",
    "\"DEC\"",
    "\"DIV\"",
    "\"END\"",
    "\"EXP\"",
    "\"FOR\"",
    "\"INT\"",
    "\"LOG\"",
    "\"MAX\"",
    "\"MD5\"",
    "\"MIN\"",
    "\"MOD\"",
    "\"NOT\"",
    "\"NOW\"",
    "\"NUM\"",
    "\"RAW\"",
    "\"SET\"",
    "\"SIN\"",
    "\"SUM\"",
    "\"TAN\"",
    "\"ACOS\"",
    "\"ASIN\"",
    "\"ATAN\"",
    "\"ATN2\"",
    "\"BLOB\"",
    "\"BOTH\"",
    "\"BYTE\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CBRT\"",
    "\"CEIL\"",
    "\"CHAR\"",
    "\"CIDR\"",
    "\"CLOB\"",
    "\"COPY\"",
    "\"CORR\"",
    "\"COSH\"",
    "\"DATE\"",
    "\"DESC\"",
    "\"DROP\"",
    "\"ELSE\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"HOST\"",
    "\"HOUR\"",
    "\"INET\"",
    "\"INT2\"",
    "\"INT4\"",
    "\"INT8\"",
    "\"INTO\"",
    "\"JOIN\"",
    "\"KILL\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LONG\"",
    "\"LPAD\"",
    "\"NODE\"",
    "\"NULL\"",
    "\"OIDS\"",
    "\"PORT\"",
    "\"REAL\"",
    "\"RPAD\"",
    "\"SHOW\"",
    "\"SIGN\"",
    "\"SOME\"",
    "\"SQRT\"",
    "\"SRID\"",
    "\"ST_M\"",
    "\"ST_X\"",
    "\"ST_Y\"",
    "\"ST_Z\"",
    "\"TEMP\"",
    "\"TEXT\"",
    "\"THEN\"",
    "\"TIME\"",
    "\"TRAN\"",
    "\"TRIM\"",
    "\"TRUE\"",
    "\"TYPE\"",
    "\"USER\"",
    "\"VIEW\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"YEAR\"",
    "\"AFTER\"",
    "\"ALTER\"",
    "\"ASCII\"",
    "\"ASKML\"",
    "\"ATAN2\"",
    "\"BEGIN\"",
    "\"BOX2D\"",
    "\"BOX3D\"",
    "\"BTRIM\"",
    "\"BYTEA\"",
    "\"CHECK\"",
    "\"CLOSE\"",
    "\"COUNT\"",
    "\"CROSS\"",
    "\"EVERY\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FIRST\"",
    "\"FIXED\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FORCE\"",
    "\"GRANT\"",
    "\"ILIKE\"",
    "\"IMAGE\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"INSTR\"",
    "\"LEAST\"",
    "\"LFILL\"",
    "\"LIMIT\"",
    "\"LOCAL\"",
    "\"LOG10\"",
    "\"LOWER\"",
    "\"LTRIM\"",
    "\"MONEY\"",
    "\"MONTH\"",
    "\"MULTI\"",
    "\"NCHAR\"",
    "\"NDIMS\"",
    "\"NODES\"",
    "\"OUTER\"",
    "\"OWNER\"",
    "\"POWER\"",
    "\"QUOTE\"",
    "\"RIGHT\"",
    "\"ROUND\"",
    "\"RTRIM\"",
    "\"SCALE\"",
    "\"STDIN\"",
    "\"TABLE\"",
    "\"TEMP.\"",
    "\"TRUNC\"",
    "\"UNION\"",
    "\"UPPER\"",
    "\"USING\"",
    "\"VALUE\"",
    "\"WHERE\"",
    "\"ABBREV\"",
    "\"AREA2D\"",
    "\"ASEWKB\"",
    "\"ASEWKT\"",
    "\"ASTEXT\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT_OR\"",
    "\"COLUMN\"",
    "\"COMMIT\"",
    "\"CONCAT\"",
    "\"CREATE\"",
    "\"CURSOR\"",
    "\"DECODE\"",
    "\"DELETE\"",
    "\"DIRECT\"",
    "\"ENCODE\"",
    "\"EQUALS\"",
    "\"ESCAPE\"",
    "\"EXISTS\"",
    "\"EXTENT\"",
    "\"FAMILY\"",
    "\"FLOAT4\"",
    "\"FLOAT8\"",
    "\"FREEZE\"",
    "\"GLOBAL\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"ISRING\"",
    "\"LENGTH\"",
    "\"MANUAL\"",
    "\"MINUTE\"",
    "\"MODIFY\"",
    "\"MODULE\"",
    "\"NRINGS\"",
    "\"NULLIF\"",
    "\"NUMBER\"",
    "\"OFFSET\"",
    "\"PARENT\"",
    "\"PUBLIC\"",
    "\"RANDOM\"",
    "\"RENAME\"",
    "\"REPEAT\"",
    "\"REVOKE\"",
    "\"ROTATE\"",
    "\"SECOND\"",
    "\"SELECT\"",
    "\"SERIAL\"",
    "\"STDDEV\"",
    "\"STDOUT\"",
    "\"STRPOS\"",
    "\"SUBSTR\"",
    "\"TO_HEX\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"VACUUM\"",
    "\"VARBIT\"",
    "\"WITHIN\"",
    "\"ZMFLAG\"",
    "\"ADDDATE\"",
    "\"ADDTIME\"",
    "\"ANALYZE\"",
    "\"BETWEEN\"",
    "\"BIT_AND\"",
    "\"BOOL_OR\"",
    "\"CEILING\"",
    "\"CLUSTER\"",
    "\"COLLECT\"",
    "\"CONVERT\"",
    "\"CURDATE\"",
    "\"CURTIME\"",
    "\"DAYNAME\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEGREES\"",
    "\"EXPLAIN\"",
    "\"EXTRACT\"",
    "\"GET_BIT\"",
    "\"INHERIT\"",
    "\"INITCAP\"",
    "\"INTEGER\"",
    "\"ISEMPTY\"",
    "\"ISVALID\"",
    "\"LEADING\"",
    "\"MACADDR\"",
    "\"MAPCHAR\"",
    "\"MASKLEN\"",
    "\"NATURAL\"",
    "\"NETMASK\"",
    "\"NETWORK\"",
    "\"NPOINTS\"",
    "\"NUMERIC\"",
    "\"OVERLAY\"",
    "\"PLACING\"",
    "\"PREPARE\"",
    "\"PUBLIC.\"",
    "\"QUARTER\"",
    "\"RADIANS\"",
    "\"REGR_R2\"",
    "\"REPLACE\"",
    "\"ROTATEX\"",
    "\"ROTATEY\"",
    "\"ROTATEZ\"",
    "\"SET_BIT\"",
    "\"SETSEED\"",
    "\"SETSRID\"",
    "\"SOUNDEX\"",
    "\"SPATIAL\"",
    "\"ST_AREA\"",
    "\"STORAGE\"",
    "\"ST_SRID\"",
    "\"ST_TEXT\"",
    "\"SUBDATE\"",
    "\"SUBTIME\"",
    "\"TINYINT\"",
    "\"TO_CHAR\"",
    "\"TO_DATE\"",
    "\"VARCHAR\"",
    "\"VAR_POP\"",
    "\"VARYING\"",
    "\"VERBOSE\"",
    "\"VERSION\"",
    "\"ADD NODE\"",
    "\"ASBINARY\"",
    "\"BOOL_AND\"",
    "\"COALESCE\"",
    "\"CONTAINS\"",
    "\"DATABASE\"",
    "\"DATEDIFF\"",
    "\"DATETIME\"",
    "\"DESCRIBE\"",
    "\"DISJOINT\"",
    "\"DISTANCE\"",
    "\"DISTINCT\"",
    "\"DROPBBOX\"",
    "\"ENDPOINT\"",
    "\"ENVELOPE\"",
    "\"EXTENT3D\"",
    "\"FORCE_2D\"",
    "\"FORCE_3D\"",
    "\"FORCE_4D\"",
    "\"GEOMETRY\"",
    "\"GET_BYTE\"",
    "\"GREATEST\"",
    "\"HOSTMASK\"",
    "\"INHERITS\"",
    "\"INTERVAL\"",
    "\"ISCLOSED\"",
    "\"ISFINITE\"",
    "\"ISSIMPLE\"",
    "\"LAST_DAY\"",
    "\"LENGTH2D\"",
    "\"LENGTH3D\"",
    "\"LOCATION\"",
    "\"LONG RAW\"",
    "\"LONGTEXT\"",
    "\"LVARCHAR\"",
    "\"MEM_SIZE\"",
    "\"NATIONAL\"",
    "\"NEXT_DAY\"",
    "\"OVERLAPS\"",
    "\"PASSWORD\"",
    "\"REGCLASS\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RESOURCE\"",
    "\"ROLLBACK\"",
    "\"SET_BYTE\"",
    "\"SETPOINT\"",
    "\"SHUTDOWN\"",
    "\"SIMPLIFY\"",
    "\"SMALLINT\"",
    "\"STANDARD\"",
    "\"ST_ASGML\"",
    "\"ST_ASKML\"",
    "\"ST_ASSVG\"",
    "\"ST_BOX2D\"",
    "\"ST_BOX3D\"",
    "\"ST_BYTEA\"",
    "\"ST_MULTI\"",
    "\"ST_NDIMS\"",
    "\"ST_POINT\"",
    "\"ST_SCALE\"",
    "\"ST_WIDTH\"",
    "\"TINYTEXT\"",
    "\"TO_ASCII\"",
    "\"TRAILING\"",
    "\"TRUNCATE\"",
    "\"UNLISTEN\"",
    "\"UNSIGNED\"",
    "\"VARCHAR2\"",
    "\"VARIANCE\"",
    "\"VAR_SAMP\"",
    "\"ZEROFILL\"",
    "\"ASHEXEWKB\"",
    "\"BIGSERIAL\"",
    "\"BROADCAST\"",
    "\"CHARACTER\"",
    "\"COVAR_POP\"",
    "\"DATE_PART\"",
    "\"DAYOFWEEK\"",
    "\"DAYOFYEAR\"",
    "\"DELIMITER\"",
    "\"DIMENSION\"",
    "\"DROP NODE\"",
    "\"FORCE_3DM\"",
    "\"FORCE_3DZ\"",
    "\"GEOMETRYN\"",
    "\"LINEMERGE\"",
    "\"LOCALTIME\"",
    "\"MONTHNAME\"",
    "\"\\\"PUBLIC\\\".\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"ST_AFFINE\"",
    "\"ST_AREA2D\"",
    "\"ST_ASEWKB\"",
    "\"ST_ASEWKT\"",
    "\"ST_ASTEXT\"",
    "\"ST_BUFFER\"",
    "\"ST_COVERS\"",
    "\"ST_EQUALS\"",
    "\"ST_EXTENT\"",
    "\"ST_FACTOR\"",
    "\"ST_HASARC\"",
    "\"ST_HEIGHT\"",
    "\"ST_ISRING\"",
    "\"ST_LENGTH\"",
    "\"ST_NRINGS\"",
    "\"ST_POINTN\"",
    "\"ST_RELATE\"",
    "\"ST_ROTATE\"",
    "\"ST_WITHIN\"",
    "\"ST_ZMFLAG\"",
    "\"SUBSTRING\"",
    "\"TEMPORARY\"",
    "\"TIMEOFDAY\"",
    "\"TIMESTAMP\"",
    "\"TO_NUMBER\"",
    "\"TRANSFORM\"",
    "\"TRANSLATE\"",
    "\"VARBINARY\"",
    "\"ADD_MONTHS\"",
    "\"BIGINTEGER\"",
    "\"BIT_LENGTH\"",
    "\"BITVARYING\"",
    "\"CONSTRAINT\"",
    "\"COVAR_SAMP\"",
    "\"DATE_TRUNC\"",
    "\"DAYOFMONTH\"",
    "\"DEALLOCATE\"",
    "\"DIFFERENCE\"",
    "\"INTERSECTS\"",
    "\"MEDIUMTEXT\"",
    "\"REFERENCES\"",
    "\"REGR_COUNT\"",
    "\"REGR_SLOPE\"",
    "\"REPLICATED\"",
    "\"SEGMENTIZE\"",
    "\"SMALLFLOAT\"",
    "\"SMALLMONEY\"",
    "\"SNAPTOGRID\"",
    "\"SPLIT_PART\"",
    "\"STARTPOINT\"",
    "\"STATISTICS\"",
    "\"ST_AZIMUTH\"",
    "\"ST_CHIP_IN\"",
    "\"ST_COLLECT\"",
    "\"ST_CROSSES\"",
    "\"STDDEV_POP\"",
    "\"ST_DWITHIN\"",
    "\"ST_GEOHASH\"",
    "\"ST_ISEMPTY\"",
    "\"ST_ISVALID\"",
    "\"ST_NPOINTS\"",
    "\"ST_POLYGON\"",
    "\"ST_REVERSE\"",
    "\"ST_ROTATEX\"",
    "\"ST_ROTATEY\"",
    "\"ST_ROTATEZ\"",
    "\"ST_SETSRID\"",
    "\"ST_SUMMARY\"",
    "\"ST_TOUCHES\"",
    "\"TABLESPACE\"",
    "\"TRANSSCALE\"",
    "\"WEEKOFYEAR\"",
    "\"BOX3DEXTENT\"",
    "\"CHAR_LENGTH\"",
    "\"PERIMETER2D\"",
    "\"PERIMETER3D\"",
    "\"QUOTE_IDENT\"",
    "\"REMOVEPOINT\"",
    "\"SET_MASKLEN\"",
    "\"ST_ADDPOINT\"",
    "\"ST_ASBINARY\"",
    "\"ST_BOUNDARY\"",
    "\"ST_CENTROID\"",
    "\"ST_CHIP_OUT\"",
    "\"ST_CONTAINS\"",
    "\"ST_COORDDIM\"",
    "\"ST_DATATYPE\"",
    "\"STDDEV_SAMP\"",
    "\"ST_DISJOINT\"",
    "\"ST_DISTANCE\"",
    "\"ST_ENDPOINT\"",
    "\"ST_ENVELOPE\"",
    "\"ST_EXTENT3D\"",
    "\"ST_FORCE_2D\"",
    "\"ST_FORCE_3D\"",
    "\"ST_FORCE_4D\"",
    "\"ST_FORCERHR\"",
    "\"ST_GEOMETRY\"",
    "\"ST_GMLTOSQL\"",
    "\"ST_ISCLOSED\"",
    "\"ST_ISSIMPLE\"",
    "\"ST_LENGTH2D\"",
    "\"ST_LENGTH3D\"",
    "\"ST_MEM_SIZE\"",
    "\"ST_OVERLAPS\"",
    "\"ST_SETPOINT\"",
    "\"ST_SIMPLIFY\"",
    "\"ST_WKBTOSQL\"",
    "\"ST_WKTTOSQL\"",
    "\"TRANSACTION\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_USER\"",
    "\"EXTERIORRING\"",
    "\"GEOMETRYTYPE\"",
    "\"GEOMFROMEWKT\"",
    "\"GEOMFROMTEXT\"",
    "\"INTERSECTION\"",
    "\"JUSTIFY_DAYS\"",
    "\"LONG VARCHAR\"",
    "\"OCTET_LENGTH\"",
    "\"SERIALIZABLE\"",
    "\"ST_ASGEOJSON\"",
    "\"ST_ASHEXEWKB\"",
    "\"ST_BUILDAREA\"",
    "\"ST_COVEREDBY\"",
    "\"ST_DIMENSION\"",
    "\"ST_FORCE_3DM\"",
    "\"ST_FORCE_3DZ\"",
    "\"ST_GEOMETRYN\"",
    "\"ST_LINEMERGE\"",
    "\"ST_MAKEPOINT\"",
    "\"ST_NUMPOINTS\"",
    "\"ST_PERIMETER\"",
    "\"ST_SETFACTOR\"",
    "\"ST_TRANSFORM\"",
    "\"ST_TRANSLATE\"",
    "\"TO_TIMESTAMP\"",
    "\"VARIANCE_POP\"",
    "\"WIDTH_BUCKET\"",
    "\"INTERIORRINGN\"",
    "\"JUSTIFY_HOURS\"",
    "\"NUMGEOMETRIES\"",
    "\"QUOTE_LITERAL\"",
    "\"SMALLDATETIME\"",
    "\"ST_ADDMEASURE\"",
    "\"ST_CONVEXHULL\"",
    "\"ST_DIFFERENCE\"",
    "\"ST_INTERSECTS\"",
    "\"ST_MAKEPOINTM\"",
    "\"ST_MEMCOLLECT\"",
    "\"ST_SEGMENTIZE\"",
    "\"ST_SNAPTOGRID\"",
    "\"ST_STARTPOINT\"",
    "\"ST_TRANSSCALE\"",
    "\"SYMDIFFERENCE\"",
    "\"VARIANCE_SAMP\"",
    "\"CURRENT_SCHEMA\"",
    "\"LINE_SUBSTRING\"",
    "\"LOCALTIMESTAMP\"",
    "\"MONTHS_BETWEEN\"",
    "\"REGEXP_REPLACE\"",
    "\"REGR_INTERCEPT\"",
    "\"ST_COMPRESSION\"",
    "\"ST_CURVETOLINE\"",
    "\"ST_FIND_EXTENT\"",
    "\"ST_GEOGFROMWKB\"",
    "\"ST_GEOMFROMGML\"",
    "\"ST_GEOMFROMKML\"",
    "\"ST_GEOMFROMWKB\"",
    "\"ST_LINEFROMWKB\"",
    "\"ST_LINETOCURVE\"",
    "\"ST_LONGESTLINE\"",
    "\"ST_MAKEPOLYGON\"",
    "\"ST_MAXDISTANCE\"",
    "\"ST_PERIMETER2D\"",
    "\"ST_PERIMETER3D\"",
    "\"ST_POLYFROMWKB\"",
    "\"ST_REMOVEPOINT\"",
    "\"CLOCK_TIMESTAMP\"",
    "\"ST_CLOSESTPOINT\"",
    "\"ST_COMBINE_BBOX\"",
    "\"ST_DFULLYWITHIN\"",
    "\"ST_EXTERIORRING\"",
    "\"ST_GEOGFROMTEXT\"",
    "\"ST_GEOMETRYTYPE\"",
    "\"ST_GEOMFROMEWKB\"",
    "\"ST_GEOMFROMEWKT\"",
    "\"ST_GEOMFROMTEXT\"",
    "\"ST_INTERSECTION\"",
    "\"ST_LINEFROMTEXT\"",
    "\"ST_MAKEENVELOPE\"",
    "\"ST_MLINEFROMWKB\"",
    "\"ST_MPOLYFROMWKB\"",
    "\"ST_POINTFROMWKB\"",
    "\"ST_POLYFROMTEXT\"",
    "\"ST_SHORTESTLINE\"",
    "\"CHARACTER_LENGTH\"",
    "\"CURRENT_DATABASE\"",
    "\"FORCE_COLLECTION\"",
    "\"JUSTIFY_INTERVAL\"",
    "\"NUMINTERIORRINGS\"",
    "\"POSTGIS_DROPBBOX\"",
    "\"ST_INTERIORRINGN\"",
    "\"ST_ISVALIDREASON\"",
    "\"ST_MLINEFROMTEXT\"",
    "\"ST_MPOINTFROMWKB\"",
    "\"ST_MPOLYFROMTEXT\"",
    "\"ST_NUMGEOMETRIES\"",
    "\"ST_POINTFROMTEXT\"",
    "\"ST_SYMDIFFERENCE\"",
    "\"ADDGEOMETRYCOLUMN\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"LINE_LOCATE_POINT\"",
    "\"ST_BDPOLYFROMTEXT\"",
    "\"ST_LINE_SUBSTRING\"",
    "\"ST_MPOINTFROMTEXT\"",
    "\"ST_ORDERINGEQUALS\"",
    "\"ST_POINTONSURFACE\"",
    "\"ST_POLYGONFROMWKB\"",
    "\"PG_CLIENT_ENCODING\"",
    "\"ST_BDMPOLYFROMTEXT\"",
    "\"ST_DISTANCE_SPHERE\"",
    "\"ST_GEOMCOLLFROMWKB\"",
    "\"ST_LENGTH_SPHEROID\"",
    "\"ST_NUMINTERIORRING\"",
    "\"ST_POLYGONFROMTEXT\"",
    "\"ST_SHIFT_LONGITUDE\"",
    "\"STATEMENT_TIMESTAMP\"",
    "\"ST_CONTAINSPROPERLY\"",
    "\"ST_FORCE_COLLECTION\"",
    "\"ST_GEOMCOLLFROMTEXT\"",
    "\"ST_MULTILINEFROMWKB\"",
    "\"ST_MULTIPOLYFROMWKB\"",
    "\"ST_NUMINTERIORRINGS\"",
    "\"ST_POSTGIS_GIST_SEL\"",
    "\"LOCATE_ALONG_MEASURE\"",
    "\"ST_COLLECTIONEXTRACT\"",
    "\"ST_DISTANCE_SPHEROID\"",
    "\"ST_GEOGRAPHYFROMTEXT\"",
    "\"ST_HAUSDORFFDISTANCE\"",
    "\"ST_LENGTH2D_SPHEROID\"",
    "\"ST_LENGTH3D_SPHEROID\"",
    "\"ST_LINE_LOCATE_POINT\"",
    "\"ST_LINESTRINGFROMWKB\"",
    "\"ST_MULTIPOINTFROMWKB\"",
    "\"ST_LINEFROMMULTIPOINT\"",
    "\"ST_MULTIPOINTFROMTEXT\"",
    "\"TRANSACTION_TIMESTAMP\"",
    "\"LINE_INTERPOLATE_POINT\"",
    "\"ST_POINT_INSIDE_CIRCLE\"",
    "\"ST_SYMMETRICDIFFERENCE\"",
    "\"LOCATE_BETWEEN_MEASURES\"",
    "\"ST_LOCATE_ALONG_MEASURE\"",
    "\"ST_MULTIPOLYGONFROMTEXT\"",
    "\"ST_POSTGIS_GIST_JOINSEL\"",
    "\"ST_LINECROSSINGDIRECTION\"",
    "\"ST_MINIMUMBOUNDINGCIRCLE\"",
    "\"ST_LINE_INTERPOLATE_POINT\"",
    "\"ST_LOCATEBETWEENELEVATIONS\"",
    "\"ST_LOCATE_BETWEEN_MEASURES\"",
    "\"ST_MULTILINESTRINGFROMTEXT\"",
    "\"ST_SIMPLIFYPRESERVETOPOLOGY\"",
    "<UNARY_SIGN_>",
    "<ORDER_BY_>",
    "<UPDATE_STAT_>",
    "<PRIMARYKEY_>",
    "<FOREIGNKEY_>",
    "<PARTITIONINGKEY_>",
    "<ROUND_ROBIN_>",
    "<WITH_XROWID_>",
    "<WITHOUT_XROWID_>",
    "<PARTITION_WITH_>",
    "<START_DB_>",
    "<WAIT_TIMEOUT_>",
    "<STOP_DB_>",
    "<CREATE_DB_>",
    "<CREATE_NODE_>",
    "<DROP_DB_>",
    "<SHOW_AGENTS_>",
    "<SHOW_STATEMENTS_>",
    "<SHOW_DATABASES_>",
    "<SHOW_TABLES_>",
    "<SHOW_TRAN_ISOLATION_>",
    "<REPEATABLE_READ_>",
    "<READ_COMMITTED_>",
    "<READ_UNCOMMITTED_>",
    "<ISOLATION_LEVEL_>",
    "<SHOW_CONSTRAINTS_>",
    "<OWNER_TO_>",
    "<SHOW_TABLE_>",
    "<SHOW_VIEW_>",
    "<SHOW_VIEWS_>",
    "<SHOW_USERS_>",
    "<FORCE_NOT_NULL_>",
    "<FORCE_QUOTE_>",
    "<ON_COMMIT_>",
    "<PRESERVE_ROWS_>",
    "<DELETE_ROWS_>",
    "<GROUP_BY_>",
    "<EXEC_>",
    "<SIMILAR_TO_>",
    "<SHOW_INDEXES_>",
    "<WITH_TIMEZONE_>",
    "<WITHOUT_TIMEZONE_>",
    "<DOUBLE_PRECISION_>",
    "<BOOLEAN_>",
    "<YEAR_FROM>",
    "<QUARTER_FROM>",
    "<MONTH_FROM>",
    "<WEEK_FROM>",
    "<DAY_FROM>",
    "<DOY_FROM>",
    "<DOW_FROM>",
    "<DECADE_FROM>",
    "<CENTURY_FROM>",
    "<HOUR_FROM>",
    "<MINUTE_FROM>",
    "<SECOND_FROM>",
    "<MILLISECOND_FROM>",
    "<MILLENNIUM_FROM>",
    "<MICROSECONDS_FROM>",
    "<EPOCH_FROM>",
    "\"POSITION\"",
    "\"VALUES\"",
    "<SINGLEDIGIT>",
    "<INT_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<SCIENTIFIC_LITERAL>",
    "<STRING_LITERAL>",
    "<PARAM_PLACE_HOLDER>",
    "<INTERVAL_LITERAL>",
    "<DATE_LITERAL>",
    "<TIME_LITERAL>",
    "<TIMESTAMP_LITERAL>",
    "<TEXT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<MACADDR_LITERAL>",
    "<CIDR_LITERAL>",
    "<INET_LITERAL>",
    "<GEOMETRY_LITERAL>",
    "<BINARY_LITERAL>",
    "<HEXDECIMAL_LITERAL>",
    "<LETTER>",
    "<IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "\",\"",
    "\".\"",
    "\"::\"",
  };

}
