//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <ADD_>
 * f1 -> ( [ <COLUMN_> ] ColumnDeclare(prn) [ <FIRST_> | <AFTER_> Identifier(prn) ] | [ Constraint(prn) ] ( PrimaryKeyDef(prn) | ForeignKeyDef(prn) | CheckDef(prn) ) )
 */
public class AddDef implements Node {
   public NodeToken f0;
   public NodeChoice f1;

   public AddDef(NodeToken n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public AddDef(NodeChoice n0) {
      f0 = new NodeToken("ADD");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

