//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <ADD_NODE_>
 * f1 -> <INT_LITERAL>
 * f2 -> ( "," <INT_LITERAL> )*
 * f3 -> [ <MANUAL_> ]
 */
public class AddNodeToDB implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeListOptional f2;
   public NodeOptional f3;

   public AddNodeToDB(NodeToken n0, NodeToken n1, NodeListOptional n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public AddNodeToDB(NodeToken n0, NodeListOptional n1, NodeOptional n2) {
      f0 = new NodeToken("ADD NODE");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

