//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> AddDef(prn)
 *       | DropDef(prn)
 *       | AlterDef(prn)
 *       | RenameDef(prn)
 *       | OwnerDef(prn)
 *       | SetTablespace(prn)
 *       | Inherit(prn)
 */
public class AlterTableActon implements Node {
   public NodeChoice f0;

   public AlterTableActon(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

