//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <MODIFY_> | <ALTER_> )
 * f1 -> [ <COLUMN_> ]
 * f2 -> AlterDefOperation(prn)
 */
public class AlterDef implements Node {
   public NodeChoice f0;
   public NodeOptional f1;
   public AlterDefOperation f2;

   public AlterDef(NodeChoice n0, NodeOptional n1, AlterDefOperation n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

