//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <SET_>
 * f1 -> ( DefaultSpec(prn) | <NOT_> <NULL_> | <STATISTICS_> <INT_LITERAL> | <STORAGE_> )
 */
public class AlterDefOperationSet implements Node {
   public NodeToken f0;
   public NodeChoice f1;

   public AlterDefOperationSet(NodeToken n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public AlterDefOperationSet(NodeChoice n0) {
      f0 = new NodeToken("SET");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

