//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <TABLESPACE_>
 * f1 -> Identifier(prn)
 * f2 -> <RENAME_>
 * f3 -> <TO_>
 * f4 -> Identifier(prn)
 */
public class AlterTableSpace implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeToken f2;
   public NodeToken f3;
   public Identifier f4;

   public AlterTableSpace(NodeToken n0, Identifier n1, NodeToken n2, NodeToken n3, Identifier n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public AlterTableSpace(Identifier n0, Identifier n1) {
      f0 = new NodeToken("TABLESPACE");
      f1 = n0;
      f2 = new NodeToken("RENAME");
      f3 = new NodeToken("TO");
      f4 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

