//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <TYPE_>
 * f1 -> types()
 * f2 -> [ <USING_> ( <STRING_LITERAL> | <NULL_> | <DATE_> | <TIME_> | <TIMESTAMP_> | <INT_LITERAL> | <DECIMAL_LITERAL> | IntervalLiterals(prn) ) ]
 */
public class AlterDefOperationType implements Node {
   public NodeToken f0;
   public types f1;
   public NodeOptional f2;

   public AlterDefOperationType(NodeToken n0, types n1, NodeOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public AlterDefOperationType(types n0, NodeOptional n1) {
      f0 = new NodeToken("TYPE");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

