//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <TABLE_>
 * f1 -> TableName(prn)
 * f2 -> AlterTableActon(prn)
 * f3 -> ( "," AlterTableActon(prn) )*
 */
public class AlterTable implements Node {
   public NodeToken f0;
   public TableName f1;
   public AlterTableActon f2;
   public NodeListOptional f3;

   public AlterTable(NodeToken n0, TableName n1, AlterTableActon n2, NodeListOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public AlterTable(TableName n0, AlterTableActon n1, NodeListOptional n2) {
      f0 = new NodeToken("TABLE");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

