//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <BEGIN_>
 * f1 -> [ ( <TRANSACTION_> | <TRAN_> | <WORK_> ) ]
 */
public class BeginTransaction implements Node {
   public NodeToken f0;
   public NodeOptional f1;

   public BeginTransaction(NodeToken n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public BeginTransaction(NodeOptional n0) {
      f0 = new NodeToken("BEGIN");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

