//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <BOX3DEXTENT_>
 */
public class Box3DExtentDataType implements Node {
   public NodeToken f0;

   public Box3DExtentDataType(NodeToken n0) {
      f0 = n0;
   }

   public Box3DExtentDataType() {
      f0 = new NodeToken("BOX3DEXTENT");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

