//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <CHARACHTER_> | <CHAR_> )
 * f1 -> [ <VARYING_> ]
 * f2 -> [ LengthSpec() ]
 */
public class CharachterDataType implements Node {
   public NodeChoice f0;
   public NodeOptional f1;
   public NodeOptional f2;

   public CharachterDataType(NodeChoice n0, NodeOptional n1, NodeOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

