//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <CHECK_>
 * f1 -> <PARENTHESIS_START_>
 * f2 -> skip_to_matching_brace(prn)
 * f3 -> <PARENTHESIS_CLOSE_>
 */
public class CheckDef implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public skip_to_matching_brace f2;
   public NodeToken f3;

   public CheckDef(NodeToken n0, NodeToken n1, skip_to_matching_brace n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public CheckDef(skip_to_matching_brace n0) {
      f0 = new NodeToken("CHECK");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

