//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( Identifier(prn) | <PARENTHESIS_START_> SQLSimpleExpression(prn) <PARENTHESIS_CLOSE_> )
 * f1 -> [ <ASC_> | <DESC_> | Identifier(prn) ]
 * f2 -> ( "," ( Identifier(prn) | <PARENTHESIS_START_> SQLSimpleExpression(prn) <PARENTHESIS_CLOSE_> ) [ <ASC_> | <DESC_> | Identifier(prn) ] )*
 */
public class columnListIndexSpec implements Node {
   public NodeChoice f0;
   public NodeOptional f1;
   public NodeListOptional f2;

   public columnListIndexSpec(NodeChoice n0, NodeOptional n1, NodeListOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

