//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <CONSTRAINT_>
 * f1 -> Identifier(prn)
 */
public class Constraint implements Node {
   public NodeToken f0;
   public Identifier f1;

   public Constraint(NodeToken n0, Identifier n1) {
      f0 = n0;
      f1 = n1;
   }

   public Constraint(Identifier n0) {
      f0 = new NodeToken("CONSTRAINT");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

