//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <CREATE_>
 * f1 -> <TABLESPACE_>
 * f2 -> Identifier(prn)
 * f3 -> TablespaceLocation(prn)
 * f4 -> ( "," TablespaceLocation(prn) )*
 */
public class CreateTablespace implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Identifier f2;
   public TablespaceLocation f3;
   public NodeListOptional f4;

   public CreateTablespace(NodeToken n0, NodeToken n1, Identifier n2, TablespaceLocation n3, NodeListOptional n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public CreateTablespace(Identifier n0, TablespaceLocation n1, NodeListOptional n2) {
      f0 = new NodeToken("CREATE");
      f1 = new NodeToken("TABLESPACE");
      f2 = n0;
      f3 = n1;
      f4 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

