//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <CREATE_> | <REPLACE_> )
 * f1 -> <VIEW_>
 * f2 -> TableName(prn)
 * f3 -> [ ColumnNameListWithParenthesis(prn) ]
 * f4 -> <AS_>
 * f5 -> SelectWithoutOrder(prn)
 */
public class createView implements Node {
   public NodeChoice f0;
   public NodeToken f1;
   public TableName f2;
   public NodeOptional f3;
   public NodeToken f4;
   public SelectWithoutOrder f5;

   public createView(NodeChoice n0, NodeToken n1, TableName n2, NodeOptional n3, NodeToken n4, SelectWithoutOrder n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public createView(NodeChoice n0, TableName n1, NodeOptional n2, SelectWithoutOrder n3) {
      f0 = n0;
      f1 = new NodeToken("VIEW");
      f2 = n1;
      f3 = n2;
      f4 = new NodeToken("AS");
      f5 = n3;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

