//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <CREATE_>
 * f1 -> <USER_>
 * f2 -> Identifier(prn)
 * f3 -> <PASSWORD_>
 * f4 -> Identifier(prn)
 * f5 -> [ <DBA_> | <RESOURCE_> | <STANDARD_> ]
 */
public class CreateUser implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Identifier f2;
   public NodeToken f3;
   public Identifier f4;
   public NodeOptional f5;

   public CreateUser(NodeToken n0, NodeToken n1, Identifier n2, NodeToken n3, Identifier n4, NodeOptional n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public CreateUser(Identifier n0, Identifier n1, NodeOptional n2) {
      f0 = new NodeToken("CREATE");
      f1 = new NodeToken("USER");
      f2 = n0;
      f3 = new NodeToken("PASSWORD");
      f4 = n1;
      f5 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

