//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DATE_>
 */
public class DateDataType implements Node {
   public NodeToken f0;

   public DateDataType(NodeToken n0) {
      f0 = n0;
   }

   public DateDataType() {
      f0 = new NodeToken("DATE");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

