//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DEALLOCATE_>
 * f1 -> [ <PREPARE_> ]
 * f2 -> Identifier(prn)
 */
public class Deallocate implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public Identifier f2;

   public Deallocate(NodeToken n0, NodeOptional n1, Identifier n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Deallocate(NodeOptional n0, Identifier n1) {
      f0 = new NodeToken("DEALLOCATE");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

