//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DECLARE_>
 * f1 -> Identifier(prn)
 * f2 -> <CURSOR_>
 * f3 -> <FOR_>
 * f4 -> Select(prn)
 */
public class DeclareCursor implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeToken f2;
   public NodeToken f3;
   public Select f4;

   public DeclareCursor(NodeToken n0, Identifier n1, NodeToken n2, NodeToken n3, Select n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public DeclareCursor(Identifier n0, Select n1) {
      f0 = new NodeToken("DECLARE");
      f1 = n0;
      f2 = new NodeToken("CURSOR");
      f3 = new NodeToken("FOR");
      f4 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

