//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DEFAULT_>
 * f1 -> SQLSimpleExpression(prn)
 */
public class DefaultSpec implements Node {
   public NodeToken f0;
   public SQLSimpleExpression f1;

   public DefaultSpec(NodeToken n0, SQLSimpleExpression n1) {
      f0 = n0;
      f1 = n1;
   }

   public DefaultSpec(SQLSimpleExpression n0) {
      f0 = new NodeToken("DEFAULT");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

