//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DELETE_>
 * f1 -> <FROM_>
 * f2 -> TableName(prn)
 * f3 -> [ WhereClause(prn) ]
 */
public class Delete implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public TableName f2;
   public NodeOptional f3;

   public Delete(NodeToken n0, NodeToken n1, TableName n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Delete(TableName n0, NodeOptional n1) {
      f0 = new NodeToken("DELETE");
      f1 = new NodeToken("FROM");
      f2 = n0;
      f3 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

