//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <DESCRIBE_> | <SHOW_TABLE_> | <SHOW_VIEW_> )
 * f1 -> TableName(prn)
 */
public class DescribeTable implements Node {
   public NodeChoice f0;
   public TableName f1;

   public DescribeTable(NodeChoice n0, TableName n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

