//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DROP_>
 * f1 -> ( <DEFAULT_> | <NOT_> <NULL_> )
 */
public class DropDefaultNotNull implements Node {
   public NodeToken f0;
   public NodeChoice f1;

   public DropDefaultNotNull(NodeToken n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public DropDefaultNotNull(NodeChoice n0) {
      f0 = new NodeToken("DROP");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

