//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DROP_>
 * f1 -> <TABLE_>
 * f2 -> TableName(prn)
 * f3 -> ( "," TableName(prn) )*
 */
public class dropTable implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public TableName f2;
   public NodeListOptional f3;

   public dropTable(NodeToken n0, NodeToken n1, TableName n2, NodeListOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public dropTable(TableName n0, NodeListOptional n1) {
      f0 = new NodeToken("DROP");
      f1 = new NodeToken("TABLE");
      f2 = n0;
      f3 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

