//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DROP_>
 * f1 -> <INDEX_>
 * f2 -> Identifier(prn)
 * f3 -> [ <ON_> TableName(prn) ]
 */
public class DropIndex implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Identifier f2;
   public NodeOptional f3;

   public DropIndex(NodeToken n0, NodeToken n1, Identifier n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public DropIndex(Identifier n0, NodeOptional n1) {
      f0 = new NodeToken("DROP");
      f1 = new NodeToken("INDEX");
      f2 = n0;
      f3 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

