//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DROP_DB_>
 * f1 -> Identifier(prn)
 * f2 -> [ <FORCE_> ]
 */
public class DropDatabase implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeOptional f2;

   public DropDatabase(NodeToken n0, Identifier n1, NodeOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public DropDatabase(Identifier n0, NodeOptional n1) {
      f0 = new NodeToken("DATABASE");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

