//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <EXPLAIN_>
 * f1 -> [ <VERBOSE_> ]
 * f2 -> Select(prn)
 */
public class Explain implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public Select f2;

   public Explain(NodeToken n0, NodeOptional n1, Select n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Explain(NodeOptional n0, Select n1) {
      f0 = new NodeToken("EXPLAIN");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

