//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <FETCH_>
 * f1 -> <INT_LITERAL>
 * f2 -> <FROM_>
 * f3 -> Identifier(prn)
 */
public class FetchCursor implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;
   public Identifier f3;

   public FetchCursor(NodeToken n0, NodeToken n1, NodeToken n2, Identifier n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public FetchCursor(NodeToken n0, Identifier n1) {
      f0 = new NodeToken("FETCH");
      f1 = n0;
      f2 = new NodeToken("FROM");
      f3 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

