//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DECIMAL_LITERAL>
 *       | <INT_LITERAL>
 *       | <SCIENTIFIC_LITERAL>
 */
public class FloatingPointNumber implements Node {
   public NodeChoice f0;

   public FloatingPointNumber(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

