//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <FLOAT_>
 * f1 -> [ LengthSpec() ]
 * f2 -> UnsignedZeroFillSpecs()
 */
public class FloatDataType implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public UnsignedZeroFillSpecs f2;

   public FloatDataType(NodeToken n0, NodeOptional n1, UnsignedZeroFillSpecs n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public FloatDataType(NodeOptional n0, UnsignedZeroFillSpecs n1) {
      f0 = new NodeToken("FLOAT");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

