//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <DELIMITER_>
 * f1 -> [ <AS_> ]
 * f2 -> <STRING_LITERAL>
 */
public class FormatDefDelimiter implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public NodeToken f2;

   public FormatDefDelimiter(NodeToken n0, NodeOptional n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public FormatDefDelimiter(NodeOptional n0) {
      f0 = new NodeToken("DELIMITER");
      f1 = n0;
      f2 = new NodeToken("'");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

