//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <FROM_>
 * f1 -> TableList(prn)
 */
public class FromClause implements Node {
   public NodeToken f0;
   public TableList f1;

   public FromClause(NodeToken n0, TableList n1) {
      f0 = n0;
      f1 = n1;
   }

   public FromClause(TableList n0) {
      f0 = new NodeToken("FROM");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

