//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <ST_TRANSSCALE_> | <TRANSSCALE_> )
 * f1 -> <PARENTHESIS_START_>
 * f2 -> SQLArgument(prn)
 * f3 -> ","
 * f4 -> SQLArgument(prn)
 * f5 -> ","
 * f6 -> SQLArgument(prn)
 * f7 -> ","
 * f8 -> SQLArgument(prn)
 * f9 -> ","
 * f10 -> SQLArgument(prn)
 * f11 -> <PARENTHESIS_CLOSE_>
 */
public class Func_ST_TRANSSCALE implements Node {
   public NodeChoice f0;
   public NodeToken f1;
   public SQLArgument f2;
   public NodeToken f3;
   public SQLArgument f4;
   public NodeToken f5;
   public SQLArgument f6;
   public NodeToken f7;
   public SQLArgument f8;
   public NodeToken f9;
   public SQLArgument f10;
   public NodeToken f11;

   public Func_ST_TRANSSCALE(NodeChoice n0, NodeToken n1, SQLArgument n2, NodeToken n3, SQLArgument n4, NodeToken n5, SQLArgument n6, NodeToken n7, SQLArgument n8, NodeToken n9, SQLArgument n10, NodeToken n11) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
      f10 = n10;
      f11 = n11;
   }

   public Func_ST_TRANSSCALE(NodeChoice n0, SQLArgument n1, SQLArgument n2, SQLArgument n3, SQLArgument n4, SQLArgument n5) {
      f0 = n0;
      f1 = new NodeToken("(");
      f2 = n1;
      f3 = new NodeToken(",");
      f4 = n2;
      f5 = new NodeToken(",");
      f6 = n3;
      f7 = new NodeToken(",");
      f8 = n4;
      f9 = new NodeToken(",");
      f10 = n5;
      f11 = new NodeToken(")");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

