//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <CASE_> SQLSimpleExpression(prn) ( <WHEN_> SQLSimpleExpression(prn) <THEN_> SQLSimpleExpression(prn) )* [ <ELSE_> SQLSimpleExpression(prn) ] <END_>
 *       | <CASE_> ( <WHEN_> SQLComplexExpression(prn) <THEN_> SQLSimpleExpression(prn) )* [ <ELSE_> SQLSimpleExpression(prn) ] <END_>
 */
public class Func_Case implements Node {
   public NodeChoice f0;

   public Func_Case(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

