//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <VERSION_>
 * f1 -> <PARENTHESIS_START_>
 * f2 -> <PARENTHESIS_CLOSE_>
 */
public class Func_Version implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;

   public Func_Version(NodeToken n0, NodeToken n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Func_Version() {
      f0 = new NodeToken("VERSION");
      f1 = new NodeToken("(");
      f2 = new NodeToken(")");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

