//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <CONVERT_>
 * f1 -> <PARENTHESIS_START_>
 * f2 -> SQLArgument(prn)
 * f3 -> ( <USING_> | "," )
 * f4 -> ( <STRING_LITERAL> | Identifier(prn) )
 * f5 -> [ "," ( <STRING_LITERAL> | Identifier(prn) ) ]
 * f6 -> <PARENTHESIS_CLOSE_>
 */
public class Func_Convert implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public SQLArgument f2;
   public NodeChoice f3;
   public NodeChoice f4;
   public NodeOptional f5;
   public NodeToken f6;

   public Func_Convert(NodeToken n0, NodeToken n1, SQLArgument n2, NodeChoice n3, NodeChoice n4, NodeOptional n5, NodeToken n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public Func_Convert(SQLArgument n0, NodeChoice n1, NodeChoice n2, NodeOptional n3) {
      f0 = new NodeToken("CONVERT");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = n1;
      f4 = n2;
      f5 = n3;
      f6 = new NodeToken(")");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

