//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <INDEX_> | <INSTR_> )
 * f1 -> <PARENTHESIS_START_>
 * f2 -> SQLArgument(prn)
 * f3 -> ","
 * f4 -> SQLArgument(prn)
 * f5 -> [ "," SQLArgument(prn) ]
 * f6 -> [ "," SQLArgument(prn) ]
 * f7 -> <PARENTHESIS_CLOSE_>
 */
public class Func_Index implements Node {
   public NodeChoice f0;
   public NodeToken f1;
   public SQLArgument f2;
   public NodeToken f3;
   public SQLArgument f4;
   public NodeOptional f5;
   public NodeOptional f6;
   public NodeToken f7;

   public Func_Index(NodeChoice n0, NodeToken n1, SQLArgument n2, NodeToken n3, SQLArgument n4, NodeOptional n5, NodeOptional n6, NodeToken n7) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
   }

   public Func_Index(NodeChoice n0, SQLArgument n1, SQLArgument n2, NodeOptional n3, NodeOptional n4) {
      f0 = n0;
      f1 = new NodeToken("(");
      f2 = n1;
      f3 = new NodeToken(",");
      f4 = n2;
      f5 = n3;
      f6 = n4;
      f7 = new NodeToken(")");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

