//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <GROUP_BY_>
 * f1 -> SQLExpressionList(prn)
 */
public class GroupByClause implements Node {
   public NodeToken f0;
   public SQLExpressionList f1;

   public GroupByClause(NodeToken n0, SQLExpressionList n1) {
      f0 = n0;
      f1 = n1;
   }

   public GroupByClause(SQLExpressionList n0) {
      f0 = new NodeToken("BY");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

