//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> [ <NO_> ]
 * f1 -> <INHERIT_>
 * f2 -> TableName(prn)
 */
public class Inherit implements Node {
   public NodeOptional f0;
   public NodeToken f1;
   public TableName f2;

   public Inherit(NodeOptional n0, NodeToken n1, TableName n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Inherit(NodeOptional n0, TableName n1) {
      f0 = n0;
      f1 = new NodeToken("INHERIT");
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

