//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> DatetimeField()
 * f1 -> <TO_>
 * f2 -> DatetimeField()
 */
public class IntervalQualifier implements Node {
   public DatetimeField f0;
   public NodeToken f1;
   public DatetimeField f2;

   public IntervalQualifier(DatetimeField n0, NodeToken n1, DatetimeField n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public IntervalQualifier(DatetimeField n0, DatetimeField n1) {
      f0 = n0;
      f1 = new NodeToken("TO");
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

