//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( "IS" [ <NOT_> ] | "=" | "!=" )
 * f1 -> ( "TRUE" | "FALSE" )
 */
public class IsBooleanClause implements Node {
   public NodeChoice f0;
   public NodeChoice f1;

   public IsBooleanClause(NodeChoice n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

