//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <IS_>
 * f1 -> [ <NOT_> ]
 * f2 -> <BINARY_LITERAL>
 */
public class IsBooleanExpression implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public NodeToken f2;

   public IsBooleanExpression(NodeToken n0, NodeOptional n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public IsBooleanExpression(NodeOptional n0) {
      f0 = new NodeToken("IS");
      f1 = n0;
      f2 = new NodeToken("'");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

