//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( "IS" [ <NOT_> ] | "=" | "!=" )
 * f1 -> "NULL"
 */
public class IsNullClause implements Node {
   public NodeChoice f0;
   public NodeToken f1;

   public IsNullClause(NodeChoice n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public IsNullClause(NodeChoice n0) {
      f0 = n0;
      f1 = new NodeToken("NULL");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

