//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <KILL_>
 * f1 -> <INT_LITERAL>
 */
public class Kill implements Node {
   public NodeToken f0;
   public NodeToken f1;

   public Kill(NodeToken n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public Kill(NodeToken n0) {
      f0 = new NodeToken("KILL");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

