//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <MACADDR_>
 */
public class MacAddrDataType implements Node {
   public NodeToken f0;

   public MacAddrDataType(NodeToken n0) {
      f0 = n0;
   }

   public MacAddrDataType() {
      f0 = new NodeToken("MACADDR");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

