//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v);
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu);

}

