//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> SQLSimpleExpression(prn)
 * f1 -> [ "ASC" | "DESC" ]
 */
public class OrderByItem implements Node {
   public SQLSimpleExpression f0;
   public NodeOptional f1;

   public OrderByItem(SQLSimpleExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

