//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <PARENTHESIS_START_>
 * f1 -> <INT_LITERAL>
 * f2 -> [ "," <INT_LITERAL> ]
 * f3 -> <PARENTHESIS_CLOSE_>
 */
public class PrecisionSpec implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeOptional f2;
   public NodeToken f3;

   public PrecisionSpec(NodeToken n0, NodeToken n1, NodeOptional n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public PrecisionSpec(NodeToken n0, NodeOptional n1) {
      f0 = new NodeToken("(");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken(")");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

