//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <SELECT_>
 *       | <INSERT_>
 *       | <UPDATE_>
 *       | <DELETE_>
 *       | <REFERENCES_>
 *       | <INDEX_>
 *       | <ALTER_>
 */
public class Privilege implements Node {
   public NodeChoice f0;

   public Privilege(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

