//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <REAL_> | <SMALLFLOAT_> | <FLOAT4_> )
 * f1 -> UnsignedZeroFillSpecs()
 */
public class RealDataType implements Node {
   public NodeChoice f0;
   public UnsignedZeroFillSpecs f1;

   public RealDataType(NodeChoice n0, UnsignedZeroFillSpecs n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

