//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <REGCLASS_>
 */
public class RegClassDataType implements Node {
   public NodeToken f0;

   public RegClassDataType(NodeToken n0) {
      f0 = n0;
   }

   public RegClassDataType() {
      f0 = new NodeToken("REGCLASS");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

