//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <RENAME_>
 * f1 -> [ <COLUMN_> ]
 * f2 -> Identifier(prn)
 * f3 -> <TO_>
 * f4 -> Identifier(prn)
 */
public class RenameDef implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public Identifier f2;
   public NodeToken f3;
   public Identifier f4;

   public RenameDef(NodeToken n0, NodeOptional n1, Identifier n2, NodeToken n3, Identifier n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public RenameDef(NodeOptional n0, Identifier n1, Identifier n2) {
      f0 = new NodeToken("RENAME");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("TO");
      f4 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

