//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <RENAME_>
 * f1 -> <TABLE_>
 * f2 -> TableName(prn)
 * f3 -> <TO_>
 * f4 -> TableName(prn)
 */
public class RenameTable implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public TableName f2;
   public NodeToken f3;
   public TableName f4;

   public RenameTable(NodeToken n0, NodeToken n1, TableName n2, NodeToken n3, TableName n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public RenameTable(TableName n0, TableName n1) {
      f0 = new NodeToken("RENAME");
      f1 = new NodeToken("TABLE");
      f2 = n0;
      f3 = new NodeToken("TO");
      f4 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

