//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> SelectWithoutOrderWithParenthesis(prn)
 * f1 -> [ OrderByClause(prn) ]
 * f2 -> [ LimitClause(prn) ]
 * f3 -> [ OffsetClause(prn) ]
 */
public class Select implements Node {
   public SelectWithoutOrderWithParenthesis f0;
   public NodeOptional f1;
   public NodeOptional f2;
   public NodeOptional f3;

   public Select(SelectWithoutOrderWithParenthesis n0, NodeOptional n1, NodeOptional n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

