//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <SELECT_>
 * f1 -> [ <ALL_> | <DISTINCT_> | <UNIQUE_> ]
 * f2 -> SelectList(prn)
 * f3 -> [ IntoClause(prn) ]
 * f4 -> [ FromClause(prn) ]
 * f5 -> [ WhereClause(prn) ]
 * f6 -> [ GroupByClause(prn) ]
 * f7 -> [ HavingClause(prn) ]
 */
public class SelectWithoutOrderAndSet implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public SelectList f2;
   public NodeOptional f3;
   public NodeOptional f4;
   public NodeOptional f5;
   public NodeOptional f6;
   public NodeOptional f7;

   public SelectWithoutOrderAndSet(NodeToken n0, NodeOptional n1, SelectList n2, NodeOptional n3, NodeOptional n4, NodeOptional n5, NodeOptional n6, NodeOptional n7) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
   }

   public SelectWithoutOrderAndSet(NodeOptional n0, SelectList n1, NodeOptional n2, NodeOptional n3, NodeOptional n4, NodeOptional n5, NodeOptional n6) {
      f0 = new NodeToken("SELECT");
      f1 = n0;
      f2 = n1;
      f3 = n2;
      f4 = n3;
      f5 = n4;
      f6 = n5;
      f7 = n6;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

