//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <SET_>
 * f1 -> <TABLESPACE_>
 * f2 -> Identifier(prn)
 */
public class SetTablespace implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Identifier f2;

   public SetTablespace(NodeToken n0, NodeToken n1, Identifier n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public SetTablespace(Identifier n0) {
      f0 = new NodeToken("SET");
      f1 = new NodeToken("TABLESPACE");
      f2 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

