//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <SHOW_>
 * f1 -> ( <IDENTIFIER> | <ALL_> | <QUOTED_IDENTIFIER> )
 */
public class ShowProperty implements Node {
   public NodeToken f0;
   public NodeChoice f1;

   public ShowProperty(NodeToken n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public ShowProperty(NodeChoice n0) {
      f0 = new NodeToken("SHOW");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

