//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <SHOW_CONSTRAINTS_>
 * f1 -> <ON_>
 * f2 -> TableName(prn)
 */
public class ShowConstraints implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public TableName f2;

   public ShowConstraints(NodeToken n0, NodeToken n1, TableName n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public ShowConstraints(TableName n0) {
      f0 = new NodeToken("CONSTRAINTS");
      f1 = new NodeToken("ON");
      f2 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

