//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <AND_>
 * f1 -> SQLUnaryLogicalExpression(prn)
 * f2 -> [ <LEFTOUTER_> ]
 */
public class SQLAndExp implements Node {
   public NodeToken f0;
   public SQLUnaryLogicalExpression f1;
   public NodeOptional f2;

   public SQLAndExp(NodeToken n0, SQLUnaryLogicalExpression n1, NodeOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public SQLAndExp(SQLUnaryLogicalExpression n0, NodeOptional n1) {
      f0 = new NodeToken("AND");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

