//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> [ <NOT_> ]
 * f1 -> <BETWEEN_>
 * f2 -> SQLSimpleExpression(prn)
 * f3 -> "AND"
 * f4 -> SQLSimpleExpression(prn)
 */
public class SQLBetweenClause implements Node {
   public NodeOptional f0;
   public NodeToken f1;
   public SQLSimpleExpression f2;
   public NodeToken f3;
   public SQLSimpleExpression f4;

   public SQLBetweenClause(NodeOptional n0, NodeToken n1, SQLSimpleExpression n2, NodeToken n3, SQLSimpleExpression n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public SQLBetweenClause(NodeOptional n0, SQLSimpleExpression n1, SQLSimpleExpression n2) {
      f0 = n0;
      f1 = new NodeToken("BETWEEN");
      f2 = n1;
      f3 = new NodeToken("AND");
      f4 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

