//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> [ <NOT_> ]
 * f1 -> <IN_>
 * f2 -> ( <PARENTHESIS_START_> SubQuery(prn) | <PARENTHESIS_START_> SQLExpressionList(prn) )
 * f3 -> <PARENTHESIS_CLOSE_>
 */
public class SQLInClause implements Node {
   public NodeOptional f0;
   public NodeToken f1;
   public NodeChoice f2;
   public NodeToken f3;

   public SQLInClause(NodeOptional n0, NodeToken n1, NodeChoice n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public SQLInClause(NodeOptional n0, NodeChoice n1) {
      f0 = n0;
      f1 = new NodeToken("IN");
      f2 = n1;
      f3 = new NodeToken(")");
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

