//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <PLUS_> | <MINUS_> | <CONCAT_> )
 * f1 -> SQLPrecedenceLevel1Expression(prn)
 */
public class SQLPrecedenceLevel2Operand implements Node {
   public NodeChoice f0;
   public SQLPrecedenceLevel1Expression f1;

   public SQLPrecedenceLevel2Operand(NodeChoice n0, SQLPrecedenceLevel1Expression n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

