//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <STAR_> | <DIVIDE_> | <MOD_> | <DIV_> | <MODULO_> | <AND_BITWISE_> | <OR_BITWISE_> | <XOR_BITWISE_> | <SHIFT_LEFT_BITWISE_> | <SHIFT_RIGHT_BITWISE_> )
 * f1 -> SQLPrecedenceLevel2Expression(prn)
 */
public class SQLPrecedenceLevel3Operand implements Node {
   public NodeChoice f0;
   public SQLPrecedenceLevel2Expression f1;

   public SQLPrecedenceLevel3Operand(NodeChoice n0, SQLPrecedenceLevel2Expression n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

