//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> SQLPrimaryExpression(prn)
 */
public class SQLPrecedenceLevel3Expression implements Node {
   public SQLPrimaryExpression f0;

   public SQLPrecedenceLevel3Expression(SQLPrimaryExpression n0) {
      f0 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

