//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> SQLPrecedenceLevel2Expression(prn)
 * f1 -> ( SQLPrecedenceLevel2Operand(prn) )*
 */
public class SQLPrecedenceLevel1Expression implements Node {
   public SQLPrecedenceLevel2Expression f0;
   public NodeListOptional f1;

   public SQLPrecedenceLevel1Expression(SQLPrecedenceLevel2Expression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

