//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> Relop(prn)
 * f1 -> ( [ "ALL" | "ANY" | "SOME" ] ( <PARENTHESIS_START_> SubQuery(prn) <PARENTHESIS_CLOSE_> | <PARENTHESIS_START_> SQLExpressionList(prn) <PARENTHESIS_CLOSE_> ) | SQLSimpleExpression(prn) )
 */
public class SQLRelationalOperatorExpression implements Node {
   public Relop f0;
   public NodeChoice f1;

   public SQLRelationalOperatorExpression(Relop n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

