//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <START_DB_>
 * f1 -> Identifier(prn)
 * f2 -> ( "," Identifier(prn) )*
 * f3 -> [ <WAIT_TIMEOUT_> <INT_LITERAL> ]
 */
public class StartDatabase implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeListOptional f2;
   public NodeOptional f3;

   public StartDatabase(NodeToken n0, Identifier n1, NodeListOptional n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public StartDatabase(Identifier n0, NodeListOptional n1, NodeOptional n2) {
      f0 = new NodeToken("DATABASE");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

