//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <STOP_DB_>
 * f1 -> Identifier(prn)
 * f2 -> ( "," Identifier(prn) )*
 */
public class StopDatabase implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeListOptional f2;

   public StopDatabase(NodeToken n0, Identifier n1, NodeListOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public StopDatabase(Identifier n0, NodeListOptional n1) {
      f0 = new NodeToken("DATABASE");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

