//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <TABLESPACE_>
 * f1 -> Identifier(prn)
 */
public class tablespaceDef implements Node {
   public NodeToken f0;
   public Identifier f1;

   public tablespaceDef(NodeToken n0, Identifier n1) {
      f0 = n0;
      f1 = n1;
   }

   public tablespaceDef(Identifier n0) {
      f0 = new NodeToken("TABLESPACE");
      f1 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

