//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <LOCATION_>
 * f1 -> stringLiteral(prn)
 * f2 -> <ON_>
 * f3 -> ( <ALL_> | ( <NODE_> | <NODES_> ) <INT_LITERAL> ( "," <INT_LITERAL> )* )
 */
public class TablespaceLocation implements Node {
   public NodeToken f0;
   public stringLiteral f1;
   public NodeToken f2;
   public NodeChoice f3;

   public TablespaceLocation(NodeToken n0, stringLiteral n1, NodeToken n2, NodeChoice n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public TablespaceLocation(stringLiteral n0, NodeChoice n1) {
      f0 = new NodeToken("LOCATION");
      f1 = n0;
      f2 = new NodeToken("ON");
      f3 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

