//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <TEXT_>
 *       | <CLOB_>
 *       | <LONG_>
 *       | <LONG_VARCHAR_>
 *       | <LONGTEXT_>
 *       | <LVARCHAR_>
 *       | <MEDIUMTEXT_>
 */
public class TextDataType implements Node {
   public NodeChoice f0;

   public TextDataType(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

