//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <TIME_>
 * f1 -> [ LengthSpec() ]
 * f2 -> [ ( <WITH_TIMEZONE_> | <WITHOUT_TIMEZONE_> ) ]
 */
public class TimeDataType implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public NodeOptional f2;

   public TimeDataType(NodeToken n0, NodeOptional n1, NodeOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public TimeDataType(NodeOptional n0, NodeOptional n1) {
      f0 = new NodeToken("TIME");
      f1 = n0;
      f2 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

