//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> <UPDATE_STAT_>
 * f1 -> ( <COLUMN_> ( <PARENTHESIS_START_> <STAR_> <PARENTHESIS_CLOSE_> | <PARENTHESIS_START_> ColumnNameList(prn) <PARENTHESIS_CLOSE_> ) <FOR_> TableName(prn) | TableName(prn) | <STAR_> )
 */
public class UpdateStats implements Node {
   public NodeToken f0;
   public NodeChoice f1;

   public UpdateStats(NodeToken n0, NodeChoice n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

